services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ebanking_app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:1414/datawarehouse
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
    depends_on:
      - db
    networks:
      - network-data

  db:
    image: postgres:alpine
    ports:
      - "1414:1414"
    command: [ "postgres", "-p", "1414" ]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: ebanking
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

networks:
  network-data:
    driver: bridge
