spring:
  datasource:
    url: jdbc:postgresql://localhost:1414/ebanking
    username: postgres
    password: 123

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
